/**
 * The deployed Worker. It serves the Next.js app through the OpenNext handler
 * and exports the room Durable Object so the app's API routes can reach it
 * through the ROOM binding in wrangler.jsonc.
 */
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "../.open-next/worker.js";

export { SlateRoom } from "./room";

export default {
  fetch: handler.fetch,
} satisfies ExportedHandler;
